import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import {AuthProvider} from '@/lib/context/AuthContext'
import "./globals.css";

const inter = Inter({ subsets: ['latin']});

export const metadata: Metadata = {
  title: "MentorMatch",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        rel: "icon",
        url: "/favicon.ico",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}